# Eventtypes used to attach CIM tags (see tags.conf) [v3.3.0]

[unifi_device_inventory]
search = sourcetype="unifi:device" OR sourcetype="unifi:device:detail"

[unifi_network_inventory]
search = sourcetype="unifi:network" OR sourcetype="unifi:network:detail"

[unifi_client_session]
search = sourcetype="unifi:client"

[unifi_device_performance]
search = sourcetype="unifi:device:stats"
