[unifi_ingest]
python.version = python3
python.required = 3.13
start_by_shell = false

[unifi_inventory]
python.version = python3
python.required = 3.13
start_by_shell = false
interval = 180

[unifi_telemetry]
python.version = python3
python.required = 3.13
start_by_shell = false
interval = 60

[unifi_reference]
python.version = python3
python.required = 3.13
start_by_shell = false
interval = 86400
