[admin:TA_unifi_ng]
match = /
members = TA_unifi_ng_account, TA_unifi_ng_settings, TA_unifi_ng_unifi_ingest, TA_unifi_ng_unifi_inventory, TA_unifi_ng_unifi_telemetry, TA_unifi_ng_unifi_reference

[admin_external:TA_unifi_ng_account]
handlertype = python
python.version = python3
handlerfile = TA_unifi_ng_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_unifi_ng_settings]
handlertype = python
python.version = python3
handlerfile = TA_unifi_ng_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_unifi_ng_unifi_ingest]
handlertype = python
python.version = python3
handlerfile = TA_unifi_ng_rh_unifi_ingest.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_unifi_ng_unifi_inventory]
handlertype = python
python.version = python3
handlerfile = TA_unifi_ng_rh_unifi_inventory.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_unifi_ng_unifi_telemetry]
handlertype = python
python.version = python3
handlerfile = TA_unifi_ng_rh_unifi_telemetry.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_unifi_ng_unifi_reference]
handlertype = python
python.version = python3
handlerfile = TA_unifi_ng_rh_unifi_reference.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
